name: FoD SAST Scan and Import

on: 
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  myjob:
    runs-on: ubuntu-latest

    steps:
      # Check out source code
      - name: Check Out Source Code
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      
      - name: Setup Fortify tools
        uses: fortify-ps/github-action/setup@main
      - name: Display versions
        run: |
          echo "PATH: $PATH"
          echo "INTERNAL_FCLI: $INTERNAL_FCLI"
          echo "Internal fcli version: $($INTERNAL_FCLI -V)"
          echo "User-specified fcli version: $(fcli -V)"
      - name: Package Code + Dependencies
        run: scancentral package $PACKAGE_OPTS -o package.zip
        env:
          PACKAGE_OPTS: "-bt mvn"
