name: Test Fortify GitHub Action

on: 
  workflow_dispatch:
  push:
    branches: [master]
    

jobs:
  fod-sast-scan:
    if: false
    strategy:
      fail-fast: false
      # Prevent running multiple FoD scans on same release simultaneously
      max-parallel: 1
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      # Check out source code
      - name: Check Out Source Code
        uses: actions/checkout@v4
      
      - name: Run FoD SAST scan
        uses: rsenden/github-actionx@main
        with:
          sast-scan: true
        env:
          FOD_URL: ${{secrets.OSS_FOD_BASE_URL}}
          FOD_TENANT: ${{secrets.OSS_FOD_TENANT}}
          FOD_USER: ${{secrets.OSS_FOD_USER}}
          FOD_PASSWORD: ${{secrets.OSS_FOD_PAT}}
          FOD_RELEASE: EightBall:New-GitHub-Action
          EXTRA_FOD_LOGIN_OPTS: --socket-timeout=60s
          EXTRA_FOD_SAST_SCAN_OPTS: --notes "These are notes from the GitHub Action"
          DO_EXPORT: true
          
  sc-sast-scan:
    if: false
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      # Check out source code
      - name: Check Out Source Code
        uses: actions/checkout@v4
      - name: Run SC-SAST SAST scan
        uses: rsenden/github-actionx@main
        with:
          sast-scan: true
        env:
          SSC_URL: ${{secrets.SSC_UAT_URL}}
          SSC_TOKEN: ${{secrets.SSC_UAT_TOKEN}}
          SSC_APPVERSION: EightBall:github
          SC_SAST_TOKEN: ${{secrets.SC_SAST_UAT_TOKEN}}
          SC_SAST_SENSOR_VERSION: 23.1.0
          DO_EXPORT: true
     
  setup-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:    
      - name: Setup fcli 1.3.1
        if: always()
        uses: rsenden/github-actionx/setup@main
        with:
          fcli: 1.3.1
      - run: fcli -V
      - name: Setup latest fcli v1
        if: always()
        uses: rsenden/github-actionx/setup@main
        with:
          fcli: v1
      - run: fcli -V
      - name: Setup fcli dev_develop 
        if: always()
        uses: rsenden/github-actionx/setup@main
        with:
          fcli: dev_develop
      - run: fcli -V
      - if: always()
        run: |
          echo "PATH: $PATH"
          echo "FCLI_INSTALL_DIR: $FCLI_INSTALL_DIR"
          echo "FCLI_BIN_DIR: $FCLI_BIN_DIR"
          echo "FCLI_CMD: $FCLI_CMD"
      - name: Setup fcli action-default
        if: always()
        uses: rsenden/github-actionx/setup@main
        with:
          fcli: action-default
      - run: fcli -V
      - if: always()
        run: |
          echo "PATH: $PATH"
          echo "FCLI_INSTALL_DIR: $FCLI_INSTALL_DIR"
          echo "FCLI_BIN_DIR: $FCLI_BIN_DIR"
          echo "FCLI_CMD: $FCLI_CMD"
  
  test-defaults:
    runs-on: ubuntu-latest
    steps:
      - uses: rsenden/github-actionx/internal/set-fod-var-defaults@main

  myjob:
    runs-on: ubuntu-latest
    if: false
    steps:
      # Check out source code
      - name: Check Out Source Code
        uses: actions/checkout@v4
      
      - name: Setup test 1
        uses: rsenden/github-actionx/setup@main
        with:
          test: |
            prop1:
              subProp1: ${{ secrets.TEST_SECRET }}
              subProp2: def
            prop2:
              sub2Prop1: xyz
              
      - name: Display test 1 info
        continue-on-error: true
        run: |
          echo "PATH: $PATH"
          echo "SC_CLIENT_CMD: $SC_CLIENT_CMD"
          echo "VULN_EXPORTER_CMD: $VULN_EXPORTER_CMD"
          echo "FOD_UPLOADER_CMD: $FOD_UPLOADER_CMD"
          echo "Fcli version on path: $(fcli -V)"
          
      - name: Setup test 2
        uses: rsenden/github-actionx/setup@main
        with:
          fcli: dev_develop
          sc-client: 22.1.0
          vuln-exporter: 2.0.3
          fod-uploader: default
      - name: Display test 2 info
        continue-on-error: true
        run: |
          echo "PATH: $PATH"
          echo "SC_CLIENT_CMD: $SC_CLIENT_CMD"
          echo "VULN_EXPORTER_CMD: $VULN_EXPORTER_CMD"
          echo "FOD_UPLOADER_CMD: $FOD_UPLOADER_CMD"
          echo "Fcli version on path: $(fcli -V)"
          echo "FCLI_CMD version: $(${FCLI_CMD} -V)"
          
      - name: Setup test 3
        uses: rsenden/github-actionx/setup@main
        with:
          fcli: 1.3.1
      - name: Display test 3 info
        continue-on-error: true
        run: |
          echo "PATH: $PATH"
          echo "SC_CLIENT_CMD: $SC_CLIENT_CMD"
          echo "VULN_EXPORTER_CMD: $VULN_EXPORTER_CMD"
          echo "FOD_UPLOADER_CMD: $FOD_UPLOADER_CMD"
          echo "Fcli version on path: $(fcli -V)"
          echo "FCLI_CMD version: $(${FCLI_CMD} -V)"
          
      - name: Setup test 4
        uses: rsenden/github-actionx/setup@main
        with:
          fcli: dev_2.0.0-beta
          export-path: false
      - name: Display test 4 info
        continue-on-error: true
        run: |
          echo "PATH: $PATH"
          echo "SC_CLIENT_CMD: $SC_CLIENT_CMD"
          echo "VULN_EXPORTER_CMD: $VULN_EXPORTER_CMD"
          echo "FOD_UPLOADER_CMD: $FOD_UPLOADER_CMD"
          echo "Fcli version on path: $(fcli -V)"
          echo "FCLI_CMD version: $(${FCLI_CMD} -V)"
              
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      
      - name: Package Code + Dependencies
        uses: rsenden/github-actionx/package@main
        env:
          PACKAGE_OPTS: "-bt mvn"
          
      - name: Display ScanCentral Client version on PATH
        continue-on-error: true
        run: |
          scancentral -version
