name: Test Fortify GitHub Action

on: 
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Check out source code
      - name: Check Out Source Code
        uses: actions/checkout@v2
      
      - name: Run FoD SAST scan
        uses: fortify-ps/github-action/fod-sast-scan@main
        env:
          FOD_URL: ${{secrets.OSS_FOD_BASE_URL}}
          FOD_TENANT: ${{secrets.OSS_FOD_TENANT}}
          FOD_USER: ${{secrets.OSS_FOD_USER}}
          FOD_PASSWORD: ${{secrets.OSS_FOD_PAT}}
          FOD_RELEASE: EightBall:New-GitHub-Action
          EXTRA_FOD_LOGIN_OPTS: --socket-timeout=1s
          EXTRA_FOD_SAST_OPTS: --notes "These are notes from the GitHub Action"
              
  myjob:
    runs-on: ubuntu-latest
    if: false
    steps:
      # Check out source code
      - name: Check Out Source Code
        uses: actions/checkout@v2
      
      - name: Setup test 1
        uses: fortify-ps/github-action/setup@main
        with:
          test: |
            prop1:
              subProp1: ${{ secrets.TEST_SECRET }}
              subProp2: def
            prop2:
              sub2Prop1: xyz
              
      - name: Display test 1 info
        continue-on-error: true
        run: |
          echo "PATH: $PATH"
          echo "SC_CLIENT_CMD: $SC_CLIENT_CMD"
          echo "VULN_EXPORTER_CMD: $VULN_EXPORTER_CMD"
          echo "FOD_UPLOADER_CMD: $FOD_UPLOADER_CMD"
          echo "Fcli version on path: $(fcli -V)"
          
      - name: Setup test 2
        uses: fortify-ps/github-action/setup@main
        with:
          fcli: dev_develop
          sc-client: 22.1.0
          vuln-exporter: 2.0.3
          fod-uploader: default
      - name: Display test 2 info
        continue-on-error: true
        run: |
          echo "PATH: $PATH"
          echo "SC_CLIENT_CMD: $SC_CLIENT_CMD"
          echo "VULN_EXPORTER_CMD: $VULN_EXPORTER_CMD"
          echo "FOD_UPLOADER_CMD: $FOD_UPLOADER_CMD"
          echo "Fcli version on path: $(fcli -V)"
          echo "FCLI_CMD version: $(${FCLI_CMD} -V)"
          
      - name: Setup test 3
        uses: fortify-ps/github-action/setup@main
        with:
          fcli: 1.3.1
      - name: Display test 3 info
        continue-on-error: true
        run: |
          echo "PATH: $PATH"
          echo "SC_CLIENT_CMD: $SC_CLIENT_CMD"
          echo "VULN_EXPORTER_CMD: $VULN_EXPORTER_CMD"
          echo "FOD_UPLOADER_CMD: $FOD_UPLOADER_CMD"
          echo "Fcli version on path: $(fcli -V)"
          echo "FCLI_CMD version: $(${FCLI_CMD} -V)"
          
      - name: Setup test 4
        uses: fortify-ps/github-action/setup@main
        with:
          fcli: dev_2.0.0-beta
          export-path: false
      - name: Display test 4 info
        continue-on-error: true
        run: |
          echo "PATH: $PATH"
          echo "SC_CLIENT_CMD: $SC_CLIENT_CMD"
          echo "VULN_EXPORTER_CMD: $VULN_EXPORTER_CMD"
          echo "FOD_UPLOADER_CMD: $FOD_UPLOADER_CMD"
          echo "Fcli version on path: $(fcli -V)"
          echo "FCLI_CMD version: $(${FCLI_CMD} -V)"
              
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      
      - name: Package Code + Dependencies
        uses: fortify-ps/github-action/package@main
        env:
          PACKAGE_OPTS: "-bt mvn"
          
      - name: Display ScanCentral Client version on PATH
        continue-on-error: true
        run: |
          scancentral -version
